#!/usr/bin/env node
/*
 * scripts/check_storage_files.cjs
 *
 * Non-destructive reconciliation tool:
 * - Requires `SUPABASE_URL` and `SUPABASE_SERVICE_KEY` (service role key) in environment.
 * - Scans `post_files` and `comment_files` rows, calls `createSignedUrl` for each object_path,
 *   and reports missing objects to stdout as CSV.
 * - Writes a preview SQL file `scripts/cleanup_missing_files_preview.sql` containing DELETE
 *   statements (commented) which you can review and run manually if desired.
 */

const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

require('dotenv').config();

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_KEY in environment.');
  console.error('Set these (service role key required) and re-run the script.');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

async function fetchAll(table) {
  const { data, error } = await supabase.from(table).select('id, bucket, object_path').limit(10000);
  if (error) throw error;
  return data || [];
}

async function existsInStorage(bucket, objectPath) {
  try {
    const { data, error } = await supabase.storage.from(bucket).createSignedUrl(objectPath, 60);
    if (error) return { ok: false, error: error.message || String(error) };
    if (!data || !data.signedURL) return { ok: false, error: 'no signed url returned' };
    return { ok: true };
  } catch (err) {
    return { ok: false, error: err?.message || String(err) };
  }
}

async function main() {
  console.log('Fetching `post_files` rows...');
  const postFiles = await fetchAll('post_files');
  console.log(`Found ${postFiles.length} post_files rows.`);

  console.log('Fetching `comment_files` rows...');
  const commentFiles = await fetchAll('comment_files');
  console.log(`Found ${commentFiles.length} comment_files rows.`);

  const missing = [];

  for (const r of postFiles) {
    const res = await existsInStorage(r.bucket, r.object_path);
    if (!res.ok) missing.push({ table: 'post_files', id: r.id, bucket: r.bucket, object_path: r.object_path, error: res.error });
  }

  for (const r of commentFiles) {
    const res = await existsInStorage(r.bucket, r.object_path);
    if (!res.ok) missing.push({ table: 'comment_files', id: r.id, bucket: r.bucket, object_path: r.object_path, error: res.error });
  }

  if (!missing.length) {
    console.log('All storage objects referenced by DB rows appear to exist. No action required.');
    return;
  }

  // Write CSV report
  const outCsv = ['table,id,bucket,object_path,error'];
  for (const m of missing) {
    const safePath = (m.object_path || '').replace(/"/g, '""');
    outCsv.push(`${m.table},${m.id},${m.bucket},"${safePath}","${(m.error||'').replace(/"/g,'""')}"`);
  }
  const csvPath = path.join(__dirname, 'missing_storage_objects.csv');
  fs.writeFileSync(csvPath, outCsv.join('\n'));
  console.log(`Wrote CSV report: ${csvPath}`);

  // Prepare preview cleanup SQL (commented deletes)
  const postIds = missing.filter(m => m.table === 'post_files').map(m => m.id);
  const commentIds = missing.filter(m => m.table === 'comment_files').map(m => m.id);

  const sqlLines = [];
  sqlLines.push('-- scripts/cleanup_missing_files_preview.sql');
  sqlLines.push('-- Generated by scripts/check_storage_files.cjs');
  sqlLines.push('-- This file contains *preview* DELETE statements for DB rows whose storage\nobjects were not found. Review and run manually with caution.');
  sqlLines.push('BEGIN;');
  if (postIds.length) {
    sqlLines.push(`-- DELETE FROM post_files WHERE id IN (${postIds.join(', ')});`);
  }
  if (commentIds.length) {
    sqlLines.push(`-- DELETE FROM comment_files WHERE id IN (${commentIds.join(', ')});`);
  }
  sqlLines.push('-- COMMIT;');

  const sqlPath = path.join(__dirname, 'cleanup_missing_files_preview.sql');
  fs.writeFileSync(sqlPath, sqlLines.join('\n') + '\n');
  console.log(`Wrote SQL preview: ${sqlPath}`);

  console.log('\nSummary:');
  console.log(`  Missing objects: ${missing.length}`);
  console.log('  - Inspect the CSV and the SQL preview. When ready, you can uncomment the DELETEs in the SQL file and run them inside a transaction.');
}

main().catch(err => {
  console.error('Error running check:', err?.message || String(err));
  process.exit(2);
});
